### ISSUE TITLE
Re-integrate frontend for public voting

### ISSUE THREAD

**Issue by Geo1088** [Geo1088/animeawards-mkii#24]
Ref #9

- [x] Routing stuff (#28)
- [x] Pull category information from API through Vuex rather than the old hack (#27)
  - [x] Pull entry information from Anilist and display it nicely
- [x] Push vote information to API (blocked on #22, #23)

**Comment by EpicTroll1365** [comment]
Resolved completely in 31c737f7925996211d46086195df8efd42ca13db
