### ISSUE TITLE
Lock characters between character cats

### ISSUE THREAD

**Issue by EpicTroll1365** [Geo1088/animeawards-mkii#36]
For character cats, we need to prevent people from voting a single character into more than one Main/Supp/Dram/Com category. Antagonist will not follow this rule.

**Comment by Geo1088** [comment]
kinda fixed in a00edea, though it's visually glitchy (backing out at the confirmation dialog results in the checkbox staying checked until you switch views)

**Comment by EpicTroll1365** [comment]
Related:

The locks we applied on characters between chara cats need to be applied on themes as well but internally. In the updated OP/ED sheet, the `title` attribute is consistent across different versions of the same theme so if a user selects two themes with the same `title`, the front-end should complain.
