### ISSUE TITLE
Navigating between tabs using the same component retains component state

### ISSUE THREAD

**Issue by EpicTroll1365** [Geo1088/animeawards-mkii#37]
Since components aren't re-rendered when you switch tabs but retain the same picker component, their state carries over until you force an update.

Example screenshots: 

![](https://files.catbox.moe/cx79y9.png)

![](https://files.catbox.moe/jr4tbv.png)

This happens when navigating between categories that have the same component for their pickers. Moving to the selections tab correctly re-renders the component.

![](https://files.catbox.moe/5kbawr.png)

Assigning to @Geo1088 since I have no clue how to go about this.

**Comment by Geo1088** [comment]
This is probably a side effect of using that big `v-else-if` chain rather than subroutes for categories, I'll see how I handled this last year

**Comment by EpicTroll1365** [comment]
Resolved in 1e54057 and 31c737f7925996211d46086195df8efd42ca13db
