### ISSUE TITLE
Display eligible entries when a user goes into the search tab in every category

### ISSUE THREAD

**Issue by EpicTroll1365** [Geo1088/animeawards-mkii#45]
To allow people to get a feel for the various options they have, we want to load in entries from the dashboard sorted alphabetically/shuffled for those categories. For other categories, we'll want to send an anilist query that pulls shows randomly from anilist.

**Comment by EpicTroll1365** [comment]
Partially resolved since this feature is now limited to dashboard cats only. Let's wait on feedback and see how the public reacts to not being able to search in Aoty.

**Comment by Geo1088** [comment]
Forgot to mention, hosts told me to try this before we roll out, so gonna try to tackle it now
