### ISSUE TITLE
Wide OP/ED searches that exclude results (due to large search results) hides excluded results from future searches

### ISSUE THREAD

**Issue by tidmiste** [Geo1088/animeawards-mkii#53]
Searching for a single letter (in this case, for OP, the letter "k" for the Kaguya OP), then attempting to narrow the search by adding more letters will prevent all previously hidden results from appearing. If the initial search yields too many results to show, all results that weren't shown initially will no longer be shown in future searches.

**Comment by DoctorWhoops** [comment]
To clarify, it's just not about adding stuff, even changing the prompt altogether (starting with a different letter) any results that were omitted from the single-letter search are omitted from all searches. I was about to submit an issue on this myself:

> There's an issue with the search in OP and ED where if you give it one-letter prompts the list it loads is so large that it starts omitting stuff from the list. If you then search for these things that were omitted in other ways (e.g. typing the full title) they won't show up, while stuff that wasn't omitted from the one-letter list works fine.
> 
> e.g. if you type 'K' then Kabukichou Sherlock doesn't show up on the list of just the letter K in OP/ED. After doing this the series doesn't show up anymore at all in searches for the category. It does find them but it doesn't display them anymore. I'd imagine this can be solved by not allowing searches of less than 3 letters like in the other category. Could you test this or try to find another solution for this?

**Comment by EpicTroll1365** [comment]
I've fforced search queries to have a minimum length of 2 characters in the new build for OP/ED as well as categories that pull entries from the dashboard. Please confirm if the issue is resolved. I probably won't be around much in the next few hours.
