### ISSUE TITLE
Directory reorganization, entry-point splitting, API splitting

### ISSUE THREAD

**Issue by EpicTroll1365** [Geo1088/animeawards-mkii#87]
The directory structure is kind of a mess and the code splitting is done automatically via vue router. The store code is a whopping 13kb of JavaScript for now too.

First we'll split the code into different directories for `Results`, `Host` and `Vote` respectively. Then we'll define webpack entrypoints and separate the router and store for each entry-point as well.

There's also the API which is effectively just one big file. We could definitely split off API routes that involve the same thing into multiple files for ease.

**Comment by Geo1088** [comment]
I wouldn't even be opposed to splitting the frontend and backend into separate repos tbh, that might help to separate concerns and force us to keep private configuration stuff out of frontend packs. Though it would also probably make deployment and testing more difficult without more automation.

**Comment by EpicTroll1365** [comment]
Turns out, this is a pretty massive issue to tackle and every other issue is blocked by the progress on this one. Progress so far:

- [x] Reorganize directory structure into something more sane
- [x] Actual entry-point splitting
- [ ] Clean up the vuex store and make sure it isn't replacing entire objects where it needs to just push a new one etc.
- [ ] Split the vuex store

- [x] Create Sequelize models and use `sequelize-connect` for `express-session`
- [ ] Rewrite the API to use Sequelize instead of raw queries
- [ ] Use foreign keys where foreign keys are needed
- [ ] An `entries` table for storing dashboard entries rather than one big json string
- [ ] Split the API routes into multiple files and make them more managable
- [ ] Get rid of better-sqlite3 and db-migrate
